"""R1 regression: concurrent autogenerated-ID minting must never produce duplicates.

Both ``core/id_generator.py`` and ``utils/id_generator.py`` read-modify-write a shared
``autogen_counters.json`` with no lock and a non-atomic write. Under concurrency two
callers can read the same counter and mint the same ID. This test drives the function
from many threads at once and asserts every minted ID is unique.

It is RED before the R1 fix (lock + atomic write) and GREEN after.
"""
import importlib
import threading

import pytest

MODULES = ["core.id_generator", "utils.id_generator"]

# A simple schema: static prefix "S-" + a 6-wide incrementable number => S-000000, S-000001, ...
SCHEMA = {
    "autogenerate_segments": [
        {"type": "static", "value": "S-"},
        {"type": "number", "length": 6},
    ]
}


@pytest.mark.concurrency
@pytest.mark.parametrize("module_name", MODULES)
def test_concurrent_id_minting_is_unique(module_name, tmp_path):
    mod = importlib.import_module(module_name)
    noun_types_path = tmp_path / "noun_types.json"
    noun_types_path.write_text("{}", encoding="utf-8")

    n_workers = 32
    existing_ids = set()  # shared snapshot; the counter file is the contended state
    results = []
    results_lock = threading.Lock()
    barrier = threading.Barrier(n_workers)
    errors = []

    def worker():
        try:
            barrier.wait()  # release all threads into the read-modify-write at once
            new_id = mod.generate_autogenerated_id(
                "Sample", SCHEMA, noun_types_path, existing_ids
            )
            with results_lock:
                results.append(new_id)
        except Exception as exc:  # surface, don't swallow
            with results_lock:
                errors.append(exc)

    threads = [threading.Thread(target=worker) for _ in range(n_workers)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()

    assert not errors, f"workers raised: {errors!r}"
    assert len(results) == n_workers
    assert len(set(results)) == len(results), (
        f"duplicate IDs minted under concurrency: "
        f"{len(results) - len(set(results))} collisions in {sorted(results)}"
    )
