# api/routers/runlog_workbench/_shared.py
"""Shared import surface + cross-cutting helpers for the runlog workbench package.

This module centralises the third-party / project imports and the small helpers
that more than one route submodule depends on (project-path resolver re-export,
linear-status refresh, run-id listing, the acceptable-extensions list, the
HANDLERS dict, etc.). All helper bodies were moved VERBATIM from the original
single-file ``runlog_workbench.py``.
"""

import sys
from pathlib import Path

# Preserve the original module's import-time side effect (added ``api/`` to
# sys.path). From this submodule, parent.parent.parent resolves to ``api/``.
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import json
import mimetypes, io, zipfile
import traceback
from datetime import datetime
from typing import Any, Dict, List, Optional, Iterable, Tuple

from fastapi import APIRouter, Body, HTTPException, Request, Query, UploadFile, File, Form
from fastapi.responses import JSONResponse, StreamingResponse
from core.errors import AppError

# Shared singletons (router + pinned package logger).
from ._router import router, log, DEBUG_ENABLED

# S3-aware filesystem shims (single source for the whole package).
from ._io_shims import (
    fs_exists, fs_is_file, fs_is_dir, fs_iterdir, fs_walk, fs_mkdirs,
    fs_open_readbin, fs_open_writebin, fs_write_bytes, fs_remove,
    fs_stat_size, fs_glob_first, make_zip_stream,
    s3_read_text, s3_write_text, fs_stat_mtime,
    _jp_list_projects, _jp_list_dirnames,
)

# -----------------------------------------------------------------------------
# Project imports that are already S3-aware for JSON/text artifacts
# -----------------------------------------------------------------------------
from api.manifest.resolver import resolve_path, resolve_data_dump_contents
from core.words.handlers.behaviors import Descriptor

from core.view_runlog import (
    prepare_runlog,
    summarize_status_as_fraction,
    collect_headers,
    flatten_entries,
)
from core.status import get_status_breakdown_core
from core.data_dump import prepare_data_dump
from core.id_generator import generate_autogenerated_id

from api.i_o import (
    load_schema,
    load_data,
    load_override,
    load_verb_group_log,
    get_verb_group_log_config,
    list_verb_groups,
    is_file_empty,
    get_noun_items,
    get_noun_schema,
    get_verb_schema,
    get_adjective_schema,
    save_json,
    save_override,
    resolve_run_id_to_test_type,  # Used by grid_save and others
    resolve_verb_group_from_test_type,
    io_list_projects,
)

# --- Imports Added from Noun Workbench for RDS-aware grid_save ---
from api.routers.noun_workbench import (
    get_project_path,    # Used by grid_save and more
)

# Cross-import preserved from the original module: it must still execute at
# import time (per the refactor contract) even though the symbol is unused here.
from core.handlers.noun import _sanitize_table_name

# Verb-context adverb handlers, unified onto core.words.handlers.Descriptor (the
# legacy core/handlers/adverbs twin tree collapsed away). Each value is a factory
# that accepts the legacy call shapes the runlog consumers use — factory(entry) and
# factory(data=entry) — and returns a Descriptor with the right behavior.
def _adverb_handler_factory(behavior_name: str):
    def _make(entry=None, *, data=None):
        return Descriptor(
            data if data is not None else (entry or {}),
            behavior_name=behavior_name,
            attaches_to="verb",
        )
    _make.__name__ = f"{behavior_name}Adverb"
    return _make

TagAdverb = _adverb_handler_factory("Tag")  # re-exported; used directly by view.py

HANDLERS = {
    "ReferenceList": _adverb_handler_factory("ReferenceList"),
    "Reference":     _adverb_handler_factory("Reference"),
    "Attribute":     _adverb_handler_factory("Attribute"),
    "Tag":           TagAdverb,
    "Picture":       _adverb_handler_factory("Picture"),
}

# -----------------------------------------------------------------------------
# Small S3-safe helpers
# -----------------------------------------------------------------------------

def _is_within(parent: Path, child: Path) -> bool:
    """
    FS/S3-safe containment check. Uses Path.relative_to (no FS access).
    """
    try:
        child.relative_to(parent)
        return True
    except Exception:
        return False

# -----------------------------------------------------------------------------
# Shared helpers
# -----------------------------------------------------------------------------

# ---- Linear-status refresh helper -------------------------------------------
def _ensure_linear_status_fresh(pp: Path, group: str, run_id: str) -> None:
    try:
        from core.status import get_linear_status_progress
        get_linear_status_progress(pp, str(run_id))
    except Exception as e:
        log.debug("[linear][ensure_fresh][error]", {"run_id": run_id, "err": repr(e)})

def _data_dumps_dir(project_path: Path, verb_group: str) -> Path:
    return resolve_path(project_path, "verbs_dir") / verb_group / "data_dumps"

def _list_run_ids(project_path: Path, verb_group: str) -> List[str]:
    base = _data_dumps_dir(project_path, verb_group)
    if not fs_exists(base):
        return []
    return sorted([p.name for p in fs_iterdir(base) if fs_is_dir(p)])

def _normalize_to_grid(data: Any) -> Dict[str, Any]:
    if isinstance(data, dict) and "headers" in data and "rows" in data:
        return {"headers": list(data["headers"]), "rows": list(data["rows"])}
    if isinstance(data, list):
        headers = sorted({k for r in data if isinstance(r, dict) for k in r.keys()})
        return {"headers": headers, "rows": data}
    if isinstance(data, dict):
        return {"headers": list(data.keys()), "rows": [data]}
    return {"headers": [], "rows": []}

def _resolve_reference_for_field(project_path: Path, noun_type: str, field: str) -> Optional[dict]:
    noun_schema = get_noun_schema(project_path, noun_type) or {}
    fields_cfg = (noun_schema.get("fields", {}) or {})
    fcfg = fields_cfg.get(field, {})
    if not isinstance(fcfg, dict):
        return None
    is_adjective = fcfg.get("type") == "adjective"
    is_reference = (fcfg.get("adjective_class") or "").lower() == "reference"
    if not (is_adjective and is_reference):
        return None

    adj_schema = get_adjective_schema(project_path, field, applies_to=noun_type) or {}
    ref_noun = adj_schema.get("reference_noun")
    if not ref_noun:
        return None

    target_schema = get_noun_schema(project_path, ref_noun) or {}
    target_pid = (
        target_schema.get("primary_id_field")
        or target_schema.get("primary_id")
        or "id"
    )
    filters = adj_schema.get("filters", {}) or {}
    return {
        "adjective": field,
        "reference_noun": str(ref_noun),
        "target_primary_id": str(target_pid),
        "filters": filters,
    }

def _resolve_duration_for_field(project_path: Path, noun_type: str, field: str) -> Optional[dict]:
    """Resolve a Duration (time-aware) adjective field on ``noun_type``.

    Returns the binding the grid needs to tick: the two bound sibling fields, the mode/unit,
    and each bound field's declared type+format so the client can parse its stored instant.
    Mirrors :func:`_resolve_reference_for_field`. Returns ``None`` if ``field`` is not a
    Duration adjective.
    """
    noun_schema = get_noun_schema(project_path, noun_type) or {}
    fields_cfg = (noun_schema.get("fields", {}) or {})
    fcfg = fields_cfg.get(field, {})
    if not isinstance(fcfg, dict):
        return None
    is_adjective = fcfg.get("type") == "adjective"
    is_duration = (fcfg.get("adjective_class") or "").lower() == "duration"
    if not (is_adjective and is_duration):
        return None

    adj_schema = get_adjective_schema(project_path, field, applies_to=noun_type) or {}

    def _meta(fname: Optional[str]) -> dict:
        cfg = fields_cfg.get(fname, {}) if fname else {}
        if not isinstance(cfg, dict):
            return {"type": None, "format": None}
        return {"type": cfg.get("type"), "format": cfg.get("format")}

    start_field = adj_schema.get("start_field") or None
    end_field = adj_schema.get("end_field") or None
    return {
        "adjective": field,
        "start_field": start_field,
        "end_field": end_field,
        "mode": adj_schema.get("mode", "elapsed"),
        "unit": adj_schema.get("unit", "auto"),
        "overdue_style": adj_schema.get("overdue_style", "negative"),
        "start_meta": _meta(start_field),
        "end_meta": _meta(end_field),
    }

def _build_noun_items_map(project_path: Path, noun_types: list[str]) -> dict[str, list[dict]]:
    out = {}
    for nt in noun_types:
        try:
            out[nt] = get_noun_items(project_path, nt)
        except Exception:
            log.warning("[noun_items_map] failed to load items; defaulting to []",
                        {"noun_type": nt}, exc_info=True)
            out[nt] = []
    return out

def _group_pid_field(project_path: Path, verb_group: str) -> str:
    cfg = get_verb_group_log_config(project_path, verb_group) or {}
    pid = (
        cfg.get("primary_id")
        or cfg.get("primaryId")
        or cfg.get("primary_id_field")
        or "run_ID"
    )
    return str(pid)

# -----------------------------------------------------------------------------
# Raw file uploads: acceptable extensions (shared by raw_files, interpret,
# downloads submodules).
# -----------------------------------------------------------------------------
_ALLOWED_EXTS = {
    ".csv", ".xlsx", ".jpeg", ".png", ".docx", ".odt", ".txt", ".pdf", ".html", ".ods", ".xcf"
}
