# api/test_page_gui.py
from __future__ import annotations

from fastapi import FastAPI, APIRouter, HTTPException, Body
from fastapi.middleware.cors import CORSMiddleware
from pathlib import Path
from typing import Any, Dict, List, Optional

from api.manifest.resolver import resolve_path, resolve_data_dump_contents
from api.i_o import (
    load_data,
    save_json,
    load_schema,
    get_noun_schema,
    get_verb_schema,
    get_adjective_schema,
    get_noun_items,
    load_override,
    resolve_run_id_to_test_type,
    append_jsonl,
    rewrite_jsonl,
    replace_jsonl_entry,
)

from core.id_generator import generate_autogenerated_id

app = FastAPI(title="Grid GUI Test Backend", version="1.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # tighten for prod
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

router = APIRouter()

# ------------------------
# Helpers
# ------------------------

def get_project_path(project: str) -> Path:
    """
    Resolve /projects/<project> using layout map (no hard-coding).
    """
    # resolve_path(Path(), "project_root") -> <repo>/projects
    projects_root = resolve_path(Path(), "project_root")
    return (projects_root / project).resolve()

def _normalize_to_grid(data: Any) -> Dict[str, Any]:
    """
    Normalize anything into {headers, rows}.
    """
    if isinstance(data, dict) and "headers" in data and "rows" in data:
        return {"headers": list(data["headers"]), "rows": list(data["rows"])}

    if isinstance(data, list):
        headers = sorted({k for r in data if isinstance(r, dict) for k in r.keys()})
        return {"headers": headers, "rows": data}

    if isinstance(data, dict):
        return {"headers": list(data.keys()), "rows": [data]}

    return {"headers": [], "rows": []}

def _data_dumps_dir(project_path: Path, verb_group: str) -> Path:
    return resolve_path(project_path, "verbs_dir") / verb_group / "data_dumps"

def _list_run_ids(project_path: Path, verb_group: str) -> List[str]:
    base = _data_dumps_dir(project_path, verb_group)
    if not base.exists():
        return []
    return sorted([p.name for p in base.iterdir() if p.is_dir()])

def _resolve_reference_for_field(project_path: Path, noun_type: str, field: str) -> Optional[dict]:
    """
    Given a noun field name, if it's an adjective of class 'Reference',
    return its target noun + target primary id + filters via the adjective schema.
    """
    noun_schema = get_noun_schema(project_path, noun_type) or {}
    fcfg = (noun_schema.get("fields", {}) or {}).get(field, {})
    if not isinstance(fcfg, dict):
        return None

    is_adjective = fcfg.get("type") == "adjective"
    is_reference = (fcfg.get("adjective_class") or "").lower() == "reference"
    if not (is_adjective and is_reference):
        return None

    # Load adjective schema by its exact 'adjective' name
    adj_schema = get_adjective_schema(project_path, field, applies_to=noun_type) or {}
    ref_noun = adj_schema.get("reference_noun")
    if not ref_noun:
        return None

    target_schema = get_noun_schema(project_path, ref_noun) or {}
    target_pid = (
        target_schema.get("primary_id_field")
        or target_schema.get("primary_id")
        or "id"
    )

    return {
        "adjective": field,
        "reference_noun": str(ref_noun),
        "target_primary_id": str(target_pid),
        "filters": adj_schema.get("filters", {}) or {},
    }

# ------------------------
# Routes used by the grid UI
# ------------------------

@router.get("/grid/runs/{project}/{verb_group}")
def grid_runs(project: str, verb_group: str):
    """
    List all run folders in verbs/{verb_group}/data_dumps.
    """
    proj = get_project_path(project)
    return {"project": project, "verb_group": verb_group, "runs": _list_run_ids(proj, verb_group)}

@router.get("/grid/load/{project}/{verb_group}/{run_id}")
def grid_load(project: str, verb_group: str, run_id: str):
    """
    Load verbs/{verb_group}/data_dumps/{run_id}/DataEntry.json
    and normalize to {headers, rows}.
    """
    proj = get_project_path(project)
    path = resolve_path(proj, "data_entry", verb_group=verb_group, run_id=run_id)
    try:
        data = load_data(path) or []
    except Exception as e:
        raise HTTPException(404, f"Load error: {e}")
    return _normalize_to_grid(data)

@router.post("/gui/grid/save/{project}/{verb_group}/{run_id}")
def grid_save(project: str, verb_group: str, run_id: str, payload: dict = Body(...)):
    """
    Save DataEntry.json and update items.jsonl with a specific key order:
    primary ID first, followed by normal fields, with underscore fields last.
    """
    import traceback
    from datetime import datetime

    proj = get_project_path(project)
    headers = list(payload.get("headers") or [])
    rows    = list(payload.get("rows") or [])

    # ---------- debug logger next to DataEntry.json ----------
    data_entry_path = resolve_path(proj, "data_entry", verb_group=verb_group, run_id=run_id)
    dump_dir = data_entry_path.parent
    dump_dir.mkdir(parents=True, exist_ok=True)
    log_path = dump_dir / "grid_save_debug.log"

    rid = datetime.utcnow().strftime("%Y%m%dT%H%M%S.%fZ")
    buf: list[str] = []
    def dbg(msg: str):
        line = f"[grid_save {rid}] {msg}"
        buf.append(line)
        try:
            with log_path.open("a", encoding="utf-8") as f:
                f.write(line + "\n")
        except Exception:
            pass

    dbg(f"start project={project} verb_group={verb_group} run_id={run_id}")
    dbg(f"incoming payload: headers={len(headers)} rows={len(rows)}")
    dbg(f"data_entry_path={data_entry_path}")

    # ---------- 1) Save DataEntry.json (preserve original shape) ----------
    try:
        existing_shape = None
        try:
            existing_shape = load_data(data_entry_path)
        except Exception:
            existing_shape = None

        if isinstance(existing_shape, dict) and "headers" in existing_shape and "rows" in existing_shape:
            # keep headers+rows shape
            save_json(data_entry_path, {"headers": headers, "rows": rows})
            dbg("DataEntry.json write OK (headers+rows)")
        else:
            # keep list-only shape (note: save_json() will pretty-print; OK for now)
            save_json(data_entry_path, rows)
            dbg("DataEntry.json write OK (list-only)")
    except Exception as e:
        dbg(f"ERROR writing DataEntry.json: {e!r}")
        raise HTTPException(400, f"Save error: {e}")

    # --- 2) Update items.jsonl with a clean, defined key order ---
    try:
        test_type = resolve_run_id_to_test_type(proj, run_id)
        if not test_type:
            # If there's no test type, we can't know the noun, so we can't proceed.
            return {"status": "DataEntry.json saved, items.jsonl skipped (no test type)."}

        verb_schema = get_verb_schema(proj, test_type) or {}
        noun_type_ref = verb_schema.get("data_entry_schema", {}).get("set_up_inputs", {}).get("noun_type_ref")
        if not noun_type_ref:
            return {"status": "DataEntry.json saved, items.jsonl skipped (no noun reference)."}

        noun_schema = get_noun_schema(proj, noun_type_ref) or {}
        pid_field = noun_schema.get("primary_id_field") or noun_schema.get("primary_id") or "id"

        items_path = resolve_path(proj, "noun_items", noun_type=noun_type_ref)
        items_path.parent.mkdir(parents=True, exist_ok=True)
        
        try:
            existing_items = get_noun_items(proj, noun_type_ref)
        except FileNotFoundError:
            existing_items = []

        other_run_items = [item for item in existing_items if isinstance(item, dict) and item.get("_runID") != run_id]

        current_run_items_with_id = []
        for r in rows:
            if isinstance(r, dict) and str(r.get(pid_field, "")).strip():
                r["_runID"] = run_id
                current_run_items_with_id.append(r)
        
        final_list = other_run_items + current_run_items_with_id

        # --- NEW: Re-order keys for consistent, readable output ---
        reordered_final_list = []
        for item in final_list:
            if not isinstance(item, dict):
                reordered_final_list.append(item)
                continue

            # 1. Start with the primary ID, if it exists in the item.
            ordered_keys = [pid_field] if pid_field in item else []
            
            # 2. Add all other normal keys (sorted alphabetically for consistency).
            normal_keys = sorted([k for k in item if k != pid_field and not k.startswith('_')])
            ordered_keys.extend(normal_keys)
            
            # 3. Add all underscore keys at the end (sorted alphabetically).
            underscore_keys = sorted([k for k in item if k.startswith('_')])
            ordered_keys.extend(underscore_keys)
            
            # Build the new dictionary with the desired key order.
            reordered_item = {k: item[k] for k in ordered_keys}
            reordered_final_list.append(reordered_item)
        # --- End of new logic ---

        rewrite_jsonl(items_path, reordered_final_list)

        return {
            "status": "Save successful",
            "items_path": str(items_path),
            "rows_written_to_items": len(current_run_items_with_id),
        }
    except Exception as e:
        error_detail = f"DataEntry.json saved, but items.jsonl update failed: {e!r}\n{traceback.format_exc()}"
        # Use a different status code to indicate partial failure.
        raise HTTPException(status_code=500, detail=error_detail)

@router.get("/grid/debug/whoami")
def whoami():
    import os
    return {
        "module": __name__,
        "file": __file__,
        "mtime": os.path.getmtime(__file__),
        "routes_hint": "this is the router you meant to edit"
    }

@router.get("/grid/dump/{project}/{verb_group}/{run_id}")
def grid_dump(project: str, verb_group: str, run_id: str):
    """
    Map of dump folder (files + subfolders) for quick UI linking.
    """
    proj = get_project_path(project)
    try:
        dump = resolve_data_dump_contents(proj, verb_group=verb_group, run_id=run_id)
    except Exception as e:
        raise HTTPException(404, str(e))

    def _p(x: Path) -> str: return str(x)
    files = {
        "data_entry": _p(dump["files"]["data_entry"]),
        "status": _p(dump["files"]["status"]),
        "adverbs": _p(dump["files"]["adverbs"]),
        "other_files": {k: _p(v) for k, v in dump["files"]["other_files"].items()},
    }
    folders = {k: {"path": _p(v["path"]), "files": [_p(f) for f in v["files"]]} for k, v in dump["folders"].items()}
    return {"project": project, "verb_group": verb_group, "run_id": run_id, "files": files, "folders": folders}

@router.get("/grid/noun_info/{project}/{noun_type}")
def grid_noun_info(project: str, noun_type: str):
    """
    Return:
      - primary_id: primary id field
      - headers_from_schema: field order for columns
      - autogenerate_id: whether the noun autogenerates its primary id
      - picture_fields: fields that are adjectives of class "Picture"
    """
    proj = get_project_path(project)
    schema = get_noun_schema(proj, noun_type)
    if not schema:
        raise HTTPException(404, f"noun_type not found: {noun_type}")

    fields = schema.get("fields", {}) or {}
    primary = (
        schema.get("primary_id_field")
        or schema.get("primary_id")
        or (next(iter(fields.keys()), "id"))
    )
    headers_from_schema = list(fields.keys())

    autogenerate_id = bool(schema.get("autogenerate_id"))
    picture_fields = [
        name
        for name, cfg in (fields or {}).items()
        if isinstance(cfg, dict)
        and cfg.get("type") == "adjective"
        and str(cfg.get("adjective_class", "")).lower() == "picture"
    ]

    return {
        "primary_id": primary,
        "headers_from_schema": headers_from_schema,
        "autogenerate_id": autogenerate_id,
        "picture_fields": picture_fields,
    }

@router.get("/grid/reference_adjectives/{project}/{noun_type}")
def grid_reference_adjectives(project: str, noun_type: str):
    """
    Reference adjectives are noun fields with:
      type == "adjective" and adjective_class == "Reference".

    For each, resolve its adjective schema to learn the target reference noun and
    its primary id key.
    """
    proj = get_project_path(project)
    noun_schema = get_noun_schema(proj, noun_type)
    if not noun_schema:
        raise HTTPException(404, f"noun_type not found: {noun_type}")

    fields = noun_schema.get("fields", {}) or {}
    detail: Dict[str, Dict[str, Any]] = {}

    for field, cfg in fields.items():
        if not isinstance(cfg, dict):
            continue
        if cfg.get("type") == "adjective" and (cfg.get("adjective_class") or "").lower() == "reference":
            ref = _resolve_reference_for_field(proj, noun_type, field)
            if ref:
                detail[field] = {
                    "reference_noun": ref["reference_noun"],
                    "target_primary_id": ref["target_primary_id"],
                    "filters": ref["filters"],
                }

    return {
        "project": project,
        "noun_type": noun_type,
        "reference_fields": list(detail.keys()),
        "detail": detail,
    }

@router.get("/grid/ref_options/{project}/{noun_type}/{field}")
def grid_ref_options(project: str, noun_type: str, field: str):
    """
    Return allowed values for a Reference adjective by reading the referenced
    noun's items.jsonl and extracting the target noun's primary id field.
    Applies simple equality filters if present in the adjective schema.
    """
    proj = get_project_path(project)
    ref = _resolve_reference_for_field(proj, noun_type, field)
    if not ref:
        return {"options": []}

    target_noun = ref["reference_noun"]
    target_pid = ref["target_primary_id"]
    filters = ref.get("filters", {}) or {}

    try:
        items = get_noun_items(proj, target_noun)
    except FileNotFoundError:
        return {"options": []}

    def pass_filters(row: dict) -> bool:
        for k, v in filters.items():
            if isinstance(v, (str, int, float, bool)) and row.get(k) != v:
                return False
        return True

    seen = set()
    options: List[str] = []
    for it in items:
        if not isinstance(it, dict):
            continue
        if not pass_filters(it):
            continue
        val = str(it.get(target_pid, "")).strip()
        if val and val not in seen:
            seen.add(val)
            options.append(val)

    return {"options": options}

@router.post("/grid/generate_id/{project}/{noun_type}")
def grid_generate_id(project: str, noun_type: str, body: dict = Body(...)):
    """
    Generate an ID using the core generator and the noun's schema.
    body: { existing_ids: [] }
    """
    proj = get_project_path(project)
    schema = get_noun_schema(proj, noun_type)
    if not schema:
        raise HTTPException(404, f"noun_type not found: {noun_type}")

    existing = set(map(str, body.get("existing_ids", [])))
    new_id = generate_autogenerated_id(
        noun_type_name=noun_type,
        noun_schema=schema,
        noun_types_path=proj / "noun_types.json",
        existing_ids=existing,
    )
    return {"id": new_id}

@router.get("/grid/retest_options/{project}/{verb_group}/{run_id}")
def grid_retest_options(project: str, verb_group: str, run_id: str):
    """
    Return a sorted list of primary IDs from prior runs that are linked to the
    current run via *any* status override whose fields reference the Run noun.

    Logic:
      1) Determine the current run's verb (test type).
      2) From that verb's schema, find every status_values entry that has a field
         with {"type": "reference", "reference_noun": "Run"} (mode may be Reference or ReferenceList).
      3) For the current run in override.json, collect all runs listed under those
         fields' labels (e.g. "retest of", "previous runs", etc).
      4) For each referenced run:
           • Resolve that run’s verb/test type.
           • From that verb schema, get noun_type_ref and then the noun’s primary_id field.
           • Read that noun’s items.jsonl and collect all primary IDs where _runID == referenced run.
      5) Return the unique, sorted list of those primary IDs.
    """

    proj = get_project_path(project)

    # (1) current run's verb/test type
    curr_test_type = resolve_run_id_to_test_type(proj, run_id)
    if not curr_test_type:
        return {"options": []}

    # (2) scan verb schema for any status entries that reference runs
    verb_types = load_schema(proj, "verb")
    verb_schema = verb_types.get(curr_test_type) or {}
    status_values = verb_schema.get("status_values", []) or []

    # build set of labels (keys we’ll look for inside override rows) that reference Run
    run_ref_labels: set[str] = set()
    for status in status_values:
        fields = status.get("fields", [])
        for f in fields:
            if isinstance(f, dict) and f.get("type") == "reference" and f.get("reference_noun") == "Run":
                label = f.get("label")
                if label:
                    run_ref_labels.add(label)

    if not run_ref_labels:
        return {"options": []}

    # (3) find overrides for this run; collect referenced run IDs from any matching labels
    overrides = load_override(proj)
    linked_runs: set[str] = set()
    for row in overrides:
        if str(row.get("run")) != str(run_id):
            continue
        # Only consider overrides that belong to the same verb as the current run
        if row.get("verb") and row.get("verb") != curr_test_type:
            continue
        for label in run_ref_labels:
            val = row.get(label)
            if isinstance(val, list):
                for r in val:
                    if isinstance(r, str) and r.strip():
                        linked_runs.add(r.strip())
            elif isinstance(val, str) and val.strip():
                linked_runs.add(val.strip())

    if not linked_runs:
        return {"options": []}

    # (4) For each linked run, resolve its noun + primary id and collect the IDs from items.jsonl
    noun_types = load_schema(proj, "noun")

    def _noun_for_run(rid: str) -> tuple[str | None, str | None]:
        """return (noun_type_ref, primary_id_field) for the run's verb."""
        test_type = resolve_run_id_to_test_type(proj, rid)
        if not test_type:
            return (None, None)
        v_schema = verb_types.get(test_type) or {}
        noun_type_ref = (
            v_schema.get("data_entry_schema", {})
            .get("set_up_inputs", {})
            .get("noun_type_ref")
        )
        if not noun_type_ref:
            return (None, None)
        n_schema = noun_types.get(noun_type_ref) or {}
        pid = n_schema.get("primary_id_field") or n_schema.get("primary_id") or "id"
        return (noun_type_ref, pid)

    options: set[str] = set()
    for prev_run in sorted(linked_runs):
        noun_type_ref, pid_field = _noun_for_run(prev_run)
        if not noun_type_ref or not pid_field:
            continue
        try:
            items = get_noun_items(proj, noun_type_ref)
        except FileNotFoundError:
            continue
        for it in items:
            if str(it.get("_runID", "")) == str(prev_run):
                pid = it.get(pid_field)
                if pid:
                    options.add(str(pid))

    return {"options": sorted(options)}


# Mount router
app.include_router(router)
