# core_audit_instances.py
# Pure logic audit engine for GIMS instances, verbs, adverbs, adjectives.
# No file I/O. Feed it already-loaded structures from your API layer.

from __future__ import annotations
from dataclasses import dataclass, asdict
from typing import Any, Dict, Iterable, List, Optional, Set, Tuple
import re
import itertools
import collections

# Debug control - set to False to disable all backend debug logging
DEBUG_ENABLED = False  # Change to True to enable debug logs

def debug(*args, **kwargs):
    """Debug print that respects DEBUG_ENABLED flag."""
    if DEBUG_ENABLED:
        # You can swap print for logging.debug if you want timestamps
        print(*args, **kwargs)

debug("[core_audit_instances] Module loaded")

# -------------------------------
# Public datatypes
# -------------------------------

Severity = str  # "error" | "warn" | "info"

@dataclass
class Finding:
    code: str                 # e.g., "N_REQUIRED_MISSING"
    severity: Severity        # "error" | "warn" | "info"
    where: Dict[str, Any]     # narrow, machine-friendly locator
    message: str              # human readable
    details: Dict[str, Any]   # extra structured context

# -------------------------------
# Type aliases (shape contracts)
# -------------------------------

# You can keep these loose (Dict[str, Any]) to avoid over-fitting to evolving schemas.
NounTypes      = Dict[str, Dict[str, Any]]     # noun_type_name -> schema dict
VerbTypes      = Dict[str, Dict[str, Any]]     # verb_name -> verb schema (incl. adverb_schema)
AdverbTypes    = Dict[str, Dict[str, Any]]     # adverb_name -> adverb type definition (with .verb, etc.)
AdjectiveTypes = Dict[str, Dict[str, Any]]     # adjective_name -> definition (class, etc.)

# Instances:
# noun_instances_by_type: { noun_type: [ {field: value, "_runID": "...", "<primary_id_field>": "..."} ] }
NounInstancesByType = Dict[str, List[Dict[str, Any]]]

# run_entries_by_group: { verb_group: [ { "_runID": str, "verb": str, "adverbs": {...}, "data_entry": {...}, ... } ] }
RunEntriesByGroup = Dict[str, List[Dict[str, Any]]]

# override_index: runID -> set of other runIDs that explicitly alias/override it
OverrideIndex = Dict[str, Set[str]]

# For noun reference resolution, we’ll use a simple index:
# noun_index: { noun_type: set(primary_ids) }
NounIndex = Dict[str, Set[str]]

# data_entry_schemas: { verb_name: { "required_headers": [...], "types": { header: "string|number|bool|date" } } }
# (If you store this inside VerbTypes["data_entry_schema"], pass it through as-is and we’ll read it there.)


# -------------------------------
# Helpers: summarization
# -------------------------------

def summarize_findings(findings: Iterable[Finding]) -> Dict[str, Any]:
    debug("[summarize_findings] Start")
    counts = collections.Counter()
    by_code = collections.Counter()
    total = 0
    for f in findings:
        total += 1
        counts[f.severity] += 1
        by_code[f.code] += 1
    summary = {
        "errors": counts.get("error", 0),
        "warnings": counts.get("warn", 0),
        "infos": counts.get("info", 0),
        "by_code": dict(by_code),
        "total": total,
    }
    debug("[summarize_findings] Done ->", summary)
    return summary


# -------------------------------
# Helpers: type & value checking
# -------------------------------

def _is_type(value: Any, t: str) -> bool:
    """Loose, pragmatic type check aligned with GIMS field types."""
    # NOTE: This is called very frequently; keep debug lightweight.
    t_orig = t
    if value is None:
        debug("[_is_type] value=None fails for type", t_orig)
        return False
    t = t.lower()
    if t in ("string", "str", "text"):
        ok = isinstance(value, str)
    elif t in ("number", "float", "double", "decimal"):
        ok = isinstance(value, (int, float)) and not isinstance(value, bool)
    elif t in ("int", "integer"):
        ok = isinstance(value, int) and not isinstance(value, bool)
    elif t in ("bool", "boolean"):
        ok = isinstance(value, bool)
    elif t == "date":
        ok = isinstance(value, str) and bool(re.match(r"^\d{4}-\d{2}-\d{2}$", value))
    elif t in ("reference", "ref"):
        ok = isinstance(value, str)
    elif t in ("enum", "tag"):
        ok = isinstance(value, (str, list))
    else:
        ok = True  # Unknown types pass
    debug("[_is_type]", repr(value), "as", t_orig, "->", ok)
    return ok


def _dedupe(seq: Iterable[Any]) -> Tuple[List[Any], List[Any]]:
    """Return (unique_in_order, duplicates_in_order)."""
    debug("[_dedupe] Start")
    seen = set()
    uniques, dups = [], []
    for x in seq:
        if x in seen:
            dups.append(x)
        else:
            seen.add(x)
            uniques.append(x)
    debug("[_dedupe] uniques:", uniques, "dups:", dups)
    return uniques, dups


# -------------------------------
# Autogenerated ID compiler
# -------------------------------

# Supported segments (aligning with your ID generator):
# - static: {"type": "static", "value": "SMP"}
# - date: {"type": "date", "format": "YYYYMMDD"}  # you control formats in backend
# - number: {"type": "number", "width": 3}        # zero-padded
# - letter: {"type": "letter", "width": 2}        # [A-Z]{width}
# - hex: {"type": "hex", "width": 4}              # [0-9A-F]{width}

_DATE_TOKEN_MAP = {
    "YYYY": r"\d{4}",
    "YY":   r"\d{2}",
    "MM":   r"\d{2}",
    "DD":   r"\d{2}",
}

def compile_autogen_regex(segments: list[dict]) -> re.Pattern:
    """
    Build a regex pattern from autogenerate_segments in noun_types.
    Supports:
      - static: {"type": "static", "value": "LOL"}
      - date:   {"type": "date", "format": "MMDDYYYY"} (case-insensitive)
      - number: {"type": "number", "width": 3} or {"length": 3}
      - hex:    {"type": "hex", "width": 4} or {"length": 4}
      - letter: {"type": "letter", "width": 2}
    """
    parts = []
    for seg in segments or []:
        stype = (seg.get("type") or "").lower()
        if stype == "static":
            val = str(seg.get("value", ""))
            parts.append(re.escape(val))

        elif stype == "date":
            fmt = str(seg.get("format", "YYYYMMDD")).upper()
            pattern = re.escape(fmt)
            for tok, rx in _DATE_TOKEN_MAP.items():
                pattern = pattern.replace(re.escape(tok), rx)
            parts.append(pattern)

        elif stype == "number":
            w = int(seg.get("width") or seg.get("length") or 1)
            parts.append(rf"\d{{{w}}}")

        elif stype == "hex":
            w = int(seg.get("width") or seg.get("length") or 1)
            parts.append(rf"[0-9A-F]{{{w}}}")

        elif stype == "letter":
            w = int(seg.get("width") or seg.get("length") or 1)
            parts.append(rf"[A-Z]{{{w}}}")

        else:
            # Fallback: accept any non-empty string
            parts.append(r".+")

    regex = "^" + "".join(parts) + "$"
    return re.compile(regex)


# -------------------------------
# Noun auditing
# -------------------------------

def audit_noun_instances(
    noun_types: NounTypes,
    noun_instances_by_type: NounInstancesByType,
    noun_index: Optional[NounIndex] = None,
) -> List[Finding]:
    debug("[audit_noun_instances] Start")
    findings: List[Finding] = []
    noun_index = noun_index or {k: set() for k in noun_instances_by_type.keys()}

    # Pre-compile ID regex per noun type if autogeneration configured
    id_regex_by_type: Dict[str, Optional[re.Pattern]] = {}
    primary_field_by_type: Dict[str, Optional[str]] = {}

    for nt_name, nt_schema in noun_types.items():
        primary_field = nt_schema.get("primary_id_field")
        primary_field_by_type[nt_name] = primary_field
        autogen = nt_schema.get("autogenerate_segments")
        id_regex_by_type[nt_name] = compile_autogen_regex(autogen) if autogen else None
        debug(f"[audit_noun_instances] NounType={nt_name} primary_field={primary_field} id_rx={id_regex_by_type[nt_name]}")

    for nt_name, instances in noun_instances_by_type.items():
        debug(f"[audit_noun_instances] Checking noun_type={nt_name} with {len(instances)} instances")
        nt_schema = noun_types.get(nt_name, {})
        required_fields: Set[str] = set(nt_schema.get("required_fields", []))
        field_types: Dict[str, str] = nt_schema.get("field_types", {}) or {}
        adjective_fields: Dict[str, Dict[str, Any]] = nt_schema.get("adjective_fields", {}) or {}
        primary_field = primary_field_by_type.get(nt_name)
        id_rx = id_regex_by_type.get(nt_name)

        for inst in instances:
            pid = inst.get(primary_field) if primary_field else None
            rid = inst.get("_runID")
            debug(f"[audit_noun_instances] Instance primary={pid} _runID={rid}")

            # Required fields present
            missing = sorted(f for f in required_fields if f not in inst or inst.get(f) in (None, ""))
            if missing:
                debug("[audit_noun_instances] Missing required fields:", missing)
                findings.append(Finding(
                    code="N_REQUIRED_MISSING",
                    severity="error",
                    where={"scope": "noun", "noun_type": nt_name, "primary": pid, "_runID": rid},
                    message=f"Missing required fields: {missing}",
                    details={"missing": missing}
                ))

            # Type checks (only for fields declared in schema)
            for field, t in field_types.items():
                if field in inst and inst[field] is not None:
                    ok = _is_type(inst[field], t)
                    if not ok:
                        debug(f"[audit_noun_instances] Type mismatch field={field} expected={t} value={inst[field]}")
                        findings.append(Finding(
                            code="N_TYPE_MISMATCH",
                            severity="error",
                            where={"scope": "noun", "noun_type": nt_name, "field": field, "primary": pid, "_runID": rid},
                            message=f"Field '{field}' has wrong type (expected {t})",
                            details={"expected": t, "value": inst[field]}
                        ))

            # Reference adjective checks (if configured on this noun type)
            for field, adj_cfg in adjective_fields.items():
                adj_class = (adj_cfg.get("class") or adj_cfg.get("adjective_class") or "").lower()
                if adj_class in ("reference", "ref"):
                    allowed_types = adj_cfg.get("reference_nouns") or adj_cfg.get("reference_noun")
                    if isinstance(allowed_types, str):
                        allowed_types = [allowed_types]
                    allowed_types = list(allowed_types or [])
                    value = inst.get(field)
                    debug(f"[audit_noun_instances] Ref check field={field} value={value} allowed_types={allowed_types}")
                    if value:
                        ok = False
                        for at in allowed_types:
                            if value in (noun_index.get(at) or set()):
                                ok = True
                                break
                        if not ok:
                            debug(f"[audit_noun_instances] Invalid reference value={value} allowed_types={allowed_types}")
                            findings.append(Finding(
                                code="N_REF_INVALID",
                                severity="error",
                                where={"scope": "noun", "noun_type": nt_name, "field": field, "primary": pid, "_runID": rid},
                                message=f"Reference '{value}' not found in allowed types {allowed_types}",
                                details={"reference_value": value, "allowed_types": allowed_types}
                            ))

            # Primary ID format (if autogeneration configured)
            if id_rx and primary_field:
                if isinstance(pid, str) and not id_rx.match(pid):
                    debug(f"[audit_noun_instances] ID format mismatch primary={pid} pattern={id_rx.pattern}")
                    findings.append(Finding(
                        code="N_ID_FORMAT",
                        severity="error",
                        where={"scope": "noun", "noun_type": nt_name, "primary": pid, "_runID": rid},
                        message=f"Primary ID '{pid}' does not match autogeneration format",
                        details={"pattern": id_rx.pattern}
                    ))

            # Primary ID field missing
            if primary_field and pid is None:
                debug(f"[audit_noun_instances] Primary ID missing field={primary_field}")
                findings.append(Finding(
                    code="N_PRIMARY_MISSING",
                    severity="error",
                    where={"scope": "noun", "noun_type": nt_name, "_runID": rid},
                    message=f"Primary ID field '{primary_field}' is missing",
                    details={}
                ))

    debug("[audit_noun_instances] Done -> findings:", len(findings))
    return findings


# -------------------------------
# Adverb ↔ Verb schema congruency
# -------------------------------

def audit_adverb_type_alignment(
    adverb_types: AdverbTypes,
    verb_types: VerbTypes,
    noun_types: NounTypes
) -> List[Finding]:
    debug("[audit_adverb_type_alignment] Start")
    findings: List[Finding] = []

    # Fast lookup for noun type existence
    known_nouns = set(noun_types.keys())
    debug("[audit_adverb_type_alignment] known_nouns:", known_nouns)

    for adv_name, adv_def in adverb_types.items():
        debug(f"[audit_adverb_type_alignment] Checking adverb='{adv_name}'")
        verb_name = adv_def.get("verb")
        if not verb_name or verb_name not in verb_types:
            debug(f"[audit_adverb_type_alignment] Unknown verb='{verb_name}' for adverb='{adv_name}'")
            findings.append(Finding(
                code="ADV_VERB_UNKNOWN",
                severity="error",
                where={"scope": "adverb_type", "adverb": adv_name},
                message=f"Adverb '{adv_name}' references unknown verb '{verb_name}'",
                details={"verb": verb_name}
            ))
            continue

        v = verb_types[verb_name]
        v_adv_schema = (v.get("adverb_schema") or {})
        if adv_name not in v_adv_schema:
            debug(f"[audit_adverb_type_alignment] Adverb '{adv_name}' missing from verb '{verb_name}' adverb_schema")
            findings.append(Finding(
                code="ADV_NOT_DECLARED_ON_VERB",
                severity="error",
                where={"scope": "adverb_type", "adverb": adv_name, "verb": verb_name},
                message=f"Adverb '{adv_name}' not declared under verb '{verb_name}' adverb_schema",
                details={}
            ))

        # Cross-check fields that matter
        left = _normalize_adverb_fields(adv_def)
        right = _normalize_adverb_fields(v_adv_schema.get(adv_name, {}))
        debug(f"[audit_adverb_type_alignment] Norm left={left}")
        debug(f"[audit_adverb_type_alignment] Norm right={right}")

        # Duplicate options inside each definition
        _, dups_l = _dedupe(left.get("valid_options_values", []))
        _, dups_r = _dedupe(right.get("valid_options_values", []))
        if dups_l:
            debug(f"[audit_adverb_type_alignment] Duplicate options (left): {sorted(set(dups_l))}")
            findings.append(Finding(
                code="ADV_OPTION_DUPLICATE",
                severity="warn",
                where={"scope": "adverb_type", "adverb": adv_name, "verb": verb_name, "side": "adverb_types"},
                message=f"Duplicate option values detected: {sorted(set(dups_l))}",
                details={"duplicates": sorted(set(dups_l))}
            ))
        if dups_r:
            debug(f"[audit_adverb_type_alignment] Duplicate options (right): {sorted(set(dups_r))}")
            findings.append(Finding(
                code="ADV_OPTION_DUPLICATE",
                severity="warn",
                where={"scope": "adverb_type", "adverb": adv_name, "verb": verb_name, "side": "verb_types"},
                message=f"Duplicate option values detected: {sorted(set(dups_r))}",
                details={"duplicates": sorted(set(dups_r))}
            ))

        # Field conflicts
        conflicts = {}
        for k in ("field_type", "required", "format"):
            lv, rv = left.get(k), right.get(k)
            if lv is not None and rv is not None and lv != rv:
                conflicts[k] = (lv, rv)
        if conflicts:
            debug(f"[audit_adverb_type_alignment] Conflicts: {conflicts}")
            findings.append(Finding(
                code="ADV_SCHEMA_CONFLICT",
                severity="error",
                where={"scope": "adverb_type", "adverb": adv_name, "verb": verb_name},
                message=f"Conflicting fields between adverb_types and verb_types: {conflicts}",
                details={"conflicts": conflicts}
            ))

        # Reference nouns must exist
        for rn in set(left.get("reference_nouns", []) + right.get("reference_nouns", [])):
            if rn not in known_nouns:
                debug(f"[audit_adverb_type_alignment] Unknown reference_noun target: {rn}")
                findings.append(Finding(
                    code="ADV_REF_TARGET_UNKNOWN",
                    severity="error",
                    where={"scope": "adverb_type", "adverb": adv_name, "verb": verb_name},
                    message=f"Reference target noun type '{rn}' does not exist",
                    details={"reference_noun": rn}
                ))

    debug("[audit_adverb_type_alignment] Done -> findings:", len(findings))
    return findings


def _normalize_adverb_fields(d: Dict[str, Any]) -> Dict[str, Any]:
    debug("[_normalize_adverb_fields] In:", d)
    # Gather possible forms
    valid_options = d.get("valid_options") or []
    values = []
    for item in valid_options:
        if isinstance(item, dict) and "value" in item:
            values.append(item["value"])
        elif isinstance(item, str):
            values.append(item)
    ref_nouns = []
    if "reference_nouns" in d and isinstance(d["reference_nouns"], list):
        ref_nouns.extend([str(x) for x in d["reference_nouns"]])
    if "reference_noun" in d and isinstance(d["reference_noun"], str):
        ref_nouns.append(d["reference_noun"])
    out = {
        "field_type": d.get("field_type"),
        "required": d.get("required"),
        "format": d.get("format"),
        "valid_options_values": values,
        "reference_nouns": ref_nouns,
    }
    debug("[_normalize_adverb_fields] Out:", out)
    return out


# -------------------------------
# Per-run validation (verbs/adverbs/data entry)
# -------------------------------

def audit_run_entries(
    run_entries_by_group: RunEntriesByGroup,
    verb_types: VerbTypes,
    noun_types: NounTypes,
    adverb_types: AdverbTypes,
    noun_index: NounIndex,
    override_index: Optional[OverrideIndex] = None,
) -> List[Finding]:
    debug("[audit_run_entries] Start")
    findings: List[Finding] = []
    override_index = override_index or {}

    # Build fast maps
    verb_by_group: Dict[str, Set[str]] = collections.defaultdict(set)
    for vname, vs in verb_types.items():
        grp = vs.get("verb_group")
        if grp:
            verb_by_group[grp].add(vname)
    debug("[audit_run_entries] verb_by_group:", {k: sorted(list(v)) for k, v in verb_by_group.items()})

    # Duplicate runID detection with override-awareness
    all_runs: List[Tuple[str, str]] = []  # (runID, group)
    for group, runs in run_entries_by_group.items():
        for r in runs:
            rid = r.get("_runID")
            if rid:
                all_runs.append((rid, group))
    debug("[audit_run_entries] total runs counted:", len(all_runs))

    dup_map = _group_duplicates([rid for rid, _ in all_runs])
    debug("[audit_run_entries] dup_map keys:", list(dup_map.keys()))

    for runid, positions in dup_map.items():
        debug(f"[audit_run_entries] Checking duplicates runid={runid} occurrences={len(positions)}")
        if len(positions) <= 1:
            continue
        covered = _duplicates_covered_by_overrides(runid, positions, override_index)
        debug(f"[audit_run_entries] override covered? {covered} for runid={runid}")
        if not covered:
            findings.append(Finding(
                code="V_RUNID_DUP_NO_OVERRIDE",
                severity="error",
                where={"scope": "run", "_runID": runid},
                message=f"Duplicate _runID '{runid}' without explicit override/alias",
                details={"count": len(positions)}
            ))

    # Validate each run
    for group, runs in run_entries_by_group.items():
        allowed_verbs = verb_by_group.get(group, set())
        debug(f"[audit_run_entries] group={group} runs={len(runs)} allowed_verbs={sorted(list(allowed_verbs))}")
        for r in runs:
            rid = r.get("_runID")
            verb_name = r.get("verb")
            debug(f"[audit_run_entries] run _runID={rid} verb={verb_name}")

            if not verb_name or verb_name not in verb_types:
                debug(f"[audit_run_entries] Unknown verb for run _runID={rid}")
                findings.append(Finding(
                    code="V_VERB_UNKNOWN",
                    severity="error",
                    where={"scope": "run", "group": group, "_runID": rid},
                    message=f"Unknown verb '{verb_name}' on run",
                    details={"verb": verb_name}
                ))
                continue

            vdef = verb_types[verb_name]
            v_group = vdef.get("verb_group")

            # Group alignment
            if v_group != group:
                debug(f"[audit_run_entries] Group mismatch _runID={rid} in={group} declared={v_group}")
                findings.append(Finding(
                    code="V_GROUP_MISMATCH",
                    severity="error",
                    where={"scope": "run", "group": group, "_runID": rid, "verb": verb_name},
                    message=f"Run is in group '{group}' but verb declares '{v_group}'",
                    details={"declared_group": v_group}
                ))

            # DataEntry schema shape (if verb defines one)
            de_schema = vdef.get("data_entry_schema") or {}
            required_headers = list(de_schema.get("required_headers", []))
            header_types: Dict[str, str] = de_schema.get("types", {}) or {}

            data_entry = r.get("data_entry")
            if required_headers or header_types:
                if not isinstance(data_entry, dict):
                    debug(f"[audit_run_entries] DataEntry missing for _runID={rid} verb={verb_name}")
                    findings.append(Finding(
                        code="V_DATAENTRY_MISSING",
                        severity="error",
                        where={"scope": "run", "_runID": rid, "verb": verb_name},
                        message=f"DataEntry is required by verb '{verb_name}' but missing or not an object",
                        details={}
                    ))
                else:
                    # Required headers
                    missing = [h for h in required_headers if h not in data_entry]
                    if missing:
                        debug(f"[audit_run_entries] DataEntry missing headers _runID={rid} missing={missing}")
                        findings.append(Finding(
                            code="V_DATAENTRY_SCHEMA_MISMATCH",
                            severity="error",
                            where={"scope": "run", "_runID": rid, "verb": verb_name},
                            message=f"DataEntry missing required headers: {missing}",
                            details={"missing": missing}
                        ))
                    # Type checks
                    for h, t in header_types.items():
                        if h in data_entry and data_entry[h] is not None and not _is_type(data_entry[h], t):
                            debug(f"[audit_run_entries] DataEntry type mismatch _runID={rid} field={h} expected={t} value={data_entry[h]}")
                            findings.append(Finding(
                                code="V_DATAENTRY_SCHEMA_MISMATCH",
                                severity="error",
                                where={"scope": "run", "_runID": rid, "verb": verb_name, "field": h},
                                message=f"DataEntry field '{h}' wrong type (expected {t})",
                                details={"expected": t, "value": data_entry[h]}
                            ))

            # Per-run adverbs validation (against verb's adverb_schema)
            r_adverbs = r.get("adverbs") or {}
            v_adv_schema = vdef.get("adverb_schema") or {}
            debug(f"[audit_run_entries] _runID={rid} adverbs provided={list(r_adverbs.keys())} schema keys={list(v_adv_schema.keys())}")

            # Required adverbs
            required_adv = [name for name, meta in v_adv_schema.items() if meta.get("required") is True]
            missing_adv = [a for a in required_adv if a not in r_adverbs]
            if missing_adv:
                debug(f"[audit_run_entries] Missing required adverbs _runID={rid} missing={missing_adv}")
                findings.append(Finding(
                    code="ADV_REQUIRED_MISSING_ON_RUN",
                    severity="error",
                    where={"scope": "run", "_runID": rid, "verb": verb_name},
                    message=f"Missing required adverbs: {missing_adv}",
                    details={"missing": missing_adv}
                ))

            # Provided adverbs must be known for this verb and pass field checks
            for adv_name, adv_value in r_adverbs.items():
                if adv_name not in v_adv_schema:
                    debug(f"[audit_run_entries] Unknown adverb for verb _runID={rid} adverb={adv_name} verb={verb_name}")
                    findings.append(Finding(
                        code="ADV_NOT_DECLARED_ON_VERB",
                        severity="error",
                        where={"scope": "run", "_runID": rid, "verb": verb_name, "adverb": adv_name},
                        message=f"Adverb '{adv_name}' not allowed for verb '{verb_name}'",
                        details={}
                    ))
                    continue

                adv_meta = _normalize_adverb_fields(v_adv_schema[adv_name])

                # Type
                ftype = adv_meta.get("field_type")
                if ftype:
                    if not _is_type(adv_value, ftype):
                        debug(f"[audit_run_entries] Adverb type mismatch _runID={rid} adverb={adv_name} expected={ftype} value={adv_value}")
                        findings.append(Finding(
                            code="ADV_TYPE_MISMATCH_ON_RUN",
                            severity="error",
                            where={"scope": "run", "_runID": rid, "verb": verb_name, "adverb": adv_name},
                            message=f"Adverb '{adv_name}' wrong type (expected {ftype})",
                            details={"expected": ftype, "value": adv_value}
                        ))

                # Options (if present)
                opts = adv_meta.get("valid_options_values", [])
                if opts:
                    if isinstance(adv_value, list):
                        # Filter out blanks when checking invalids
                        invalid = [v for v in adv_value if v not in opts and v not in (None, "")]
                    else:
                        if adv_value in (None, ""):
                            invalid = []
                        else:
                            invalid = [] if adv_value in opts else [adv_value]

                    if invalid:
                        findings.append(Finding(
                            code="ADV_OPTION_INVALID",
                            severity="error",
                            where={"scope": "run", "_runID": rid, "verb": verb_name, "adverb": adv_name},
                            message=f"Adverb value(s) not in valid options: {invalid}",
                            details={"invalid": invalid, "valid": opts}
                        ))

                # Reference resolution (if reference_noun(s))
                adv_class = (adverb_types.get(adv_name, {}).get("adverb_class") or "").lower()
                ref_nouns = adv_meta.get("reference_nouns", [])
                if ref_nouns:
                    # Normalize values based on adverb_class
                    if adv_class == "referencelist":
                        raw_values = adv_value if isinstance(adv_value, list) else [adv_value]
                    elif adv_class == "reference":
                        raw_values = [adv_value] if adv_value is not None else []
                    else:
                        raw_values = []

                    # Flatten nested lists
                    values = []
                    for rv in raw_values:
                        if isinstance(rv, (list, tuple, set)):
                            values.extend(rv)
                        else:
                            values.append(rv)

                    # Now check each scalar
                    for v in values:
                        # Skip empty / unset values
                        if v in (None, "", []):
                            continue
                        if not isinstance(v, (str, int, float)):
                            continue
                        ok = any(v in (noun_index.get(nt) or set()) for nt in ref_nouns)
                        if not ok:
                            findings.append(Finding(
                                code="ADV_REF_INVALID_ON_RUN",
                                severity="error",
                                where={"scope": "run", "_runID": rid, "verb": verb_name, "adverb": adv_name},
                                message=f"Adverb reference '{v}' not found in allowed noun types {ref_nouns}",
                                details={"value": v, "allowed_types": ref_nouns}
                            ))

    debug("[audit_run_entries] Done -> findings:", len(findings))
    return findings


def _group_duplicates(ids: Iterable[str]) -> Dict[str, List[int]]:
    """Return id -> list of positions (indices). Positions are only used for counting here."""
    debug("[_group_duplicates] Start")
    positions: Dict[str, List[int]] = {}
    for idx, rid in enumerate(ids):
        positions.setdefault(rid, []).append(idx)
    result = {k: v for k, v in positions.items() if len(v) > 1}
    debug("[_group_duplicates] Result keys:", list(result.keys()))
    return result


def _duplicates_covered_by_overrides(runid: str, positions: List[int], override_index: OverrideIndex) -> bool:
    """
    Decide if duplicate runIDs are explicitly allowed via overrides/aliases.
    Strategy:
    - If override_index contains runid -> aliases where size >= len(positions)-1, consider covered.
    - Or if any alias key maps to this runid similarly.
    """
    debug(f"[_duplicates_covered_by_overrides] runid={runid} occurrences={len(positions)}")
    needed = len(positions) - 1
    if needed <= 0:
        debug("[_duplicates_covered_by_overrides] needed<=0 -> True")
        return True
    aliases = override_index.get(runid, set())
    debug(f"[_duplicates_covered_by_overrides] aliases for {runid} -> {aliases} needed={needed}")
    if len(aliases) >= needed:
        debug("[_duplicates_covered_by_overrides] Covered by direct aliases")
        return True
    # Check reciprocal keys that alias to this runid
    back_refs = [k for k, vs in override_index.items() if runid in vs]
    debug(f"[_duplicates_covered_by_overrides] back_refs -> {back_refs}")
    for k in back_refs:
        if len(override_index.get(k, set())) >= needed:
            debug("[_duplicates_covered_by_overrides] Covered by reciprocal alias")
            return True
    debug("[_duplicates_covered_by_overrides] Not covered")
    return False


# -------------------------------
# Adjective ↔ Noun type alignment (schema level)
# -------------------------------

def audit_adjective_alignment(
    noun_types: NounTypes,
    adjective_types: AdjectiveTypes
) -> List[Finding]:
    debug("[audit_adjective_alignment] Start")
    findings: List[Finding] = []

    # Build a lookup of adjective name -> class
    adj_classes = {name: (d.get("adjective_class") or d.get("class") or "").lower()
                   for name, d in adjective_types.items()}
    debug("[audit_adjective_alignment] adj_classes:", adj_classes)

    for nt_name, nt_schema in noun_types.items():
        adj_fields: Dict[str, Dict[str, Any]] = nt_schema.get("adjective_fields", {}) or {}
        debug(f"[audit_adjective_alignment] noun_type={nt_name} fields={list(adj_fields.keys())}")
        for field, cfg in adj_fields.items():
            declared_class = (cfg.get("adjective_class") or cfg.get("class") or "").lower()
            adj_name = cfg.get("adjective") or field  # if you store by name, keep this flexible
            if adj_name in adjective_types:
                real_class = adj_classes.get(adj_name, "")
                if declared_class and real_class and declared_class != real_class:
                    debug(f"[audit_adjective_alignment] Class mismatch noun_type={nt_name} field={field} declared={declared_class} actual={real_class}")
                    findings.append(Finding(
                        code="ADJ_CLASS_MISMATCH",
                        severity="error",
                        where={"scope": "noun_type", "noun_type": nt_name, "field": field, "adjective": adj_name},
                        message=f"Adjective class mismatch: {declared_class} vs {real_class}",
                        details={"declared": declared_class, "actual": real_class}
                    ))
            else:
                debug(f"[audit_adjective_alignment] Unknown adjective type noun_type={nt_name} field={field} adj={adj_name}")
                findings.append(Finding(
                    code="ADJ_TYPE_UNKNOWN",
                    severity="error",
                    where={"scope": "noun_type", "noun_type": nt_name, "field": field, "adjective": adj_name},
                    message=f"Unknown adjective type '{adj_name}' referenced by noun type '{nt_name}'",
                    details={}
                ))

    debug("[audit_adjective_alignment] Done -> findings:", len(findings))
    return findings


# -------------------------------
# Orchestration entrypoints
# -------------------------------

def audit_all(
    *,
    noun_types: NounTypes,
    verb_types: VerbTypes,
    adverb_types: AdverbTypes,
    adjective_types: AdjectiveTypes,
    noun_instances_by_type: NounInstancesByType,
    run_entries_by_group: RunEntriesByGroup,
    noun_index: Optional[NounIndex] = None,
    override_index: Optional[OverrideIndex] = None,
) -> Dict[str, Any]:
    """
    Perform all instance-level audits (no filesystem, no interpretation).
    Returns a dict with `findings` (list of Finding as dict) and `summary`.
    """
    debug("[audit_all] Start")
    # Build noun_index if not provided
    if noun_index is None:
        debug("[audit_all] Building noun_index from noun_instances_by_type")
        noun_index = {
            k: {
                inst.get(noun_types.get(k, {}).get("primary_id_field"))
                for inst in v
                if inst.get(noun_types.get(k, {}).get("primary_id_field"))
            }
            for k, v in noun_instances_by_type.items()
        }
    debug("[audit_all] noun_index keys:", {k: len(v) for k, v in noun_index.items()})
    override_index = override_index or {}
    debug("[audit_all] override_index keys:", list(override_index.keys()))

    findings: List[Finding] = []

    # Nouns
    n_findings = audit_noun_instances(noun_types, noun_instances_by_type, noun_index)
    findings += n_findings
    debug("[audit_all] Noun findings:", len(n_findings))

    # Adverbs vs Verbs
    adv_type_findings = audit_adverb_type_alignment(adverb_types, verb_types, noun_types)
    findings += adv_type_findings
    debug("[audit_all] Adverb-type findings:", len(adv_type_findings))

    # Adjectives vs Nouns
    adj_findings = audit_adjective_alignment(noun_types, adjective_types)
    findings += adj_findings
    debug("[audit_all] Adjective findings:", len(adj_findings))

    # Runs
    run_findings = audit_run_entries(run_entries_by_group, verb_types, noun_types, adverb_types, noun_index, override_index)
    findings += run_findings
    debug("[audit_all] Run findings:", len(run_findings))

    # Convert to serializable output
    as_dicts = [asdict(f) for f in findings]
    summary = summarize_findings(findings)
    debug("[audit_all] Done. Total findings:", len(as_dicts))
    return {
        "findings": as_dicts,
        "summary": summary,
    }


# -------------------------------
# Minimal self-test (optional)
# -------------------------------

if __name__ == "__main__":
    debug("[__main__] Running smoke test")
    noun_types = {
        "Sample": {
            "primary_id_field": "SampleID",
            "required_fields": ["SampleID", "Matrix"],
            "field_types": {"SampleID": "string", "Matrix": "string"},
            "adjective_fields": {
                "Parent": {"adjective_class": "Reference", "reference_nouns": ["Sample"]}
            },
            "autogenerate_segments": [
                {"type": "date", "format": "YYYYMMDD"},
                {"type": "static", "value": "-"},
                {"type": "number", "width": 3}
            ],
        }
    }
    noun_instances_by_type = {
        "Sample": [
            {"SampleID": "20250101-001", "Matrix": "Plant", "_runID": "R1"},
            {"SampleID": "bad-format", "Matrix": "Plant", "_runID": "R2", "Parent": "20250101-001"},
        ]
    }
    noun_index = {"Sample": {"20250101-001"}}

    verb_types = {
        "Test": {
            "verb_name": "Test",
            "verb_group": "General",
            "data_entry_schema": {"required_headers": ["Instrument"], "types": {"Instrument": "string"}},
            "adverb_schema": {
                "tomato": {"valid_options": [{"value": "q", "display_in_label": True}],
                           "required": True,
                           "field_type": "string"},
            }
        }
    }
    adverb_types = {
        "tomato": {"adverb": "tomato", "verb": "Test",
                   "valid_options": [{"value": "q", "display_in_label": True}, {"value": "q"}],
                   "adverb_class": "Tag"}
    }
    adjective_types = {
        "Reference": {"adjective_class": "reference"}  # simplistic placeholder
    }
    run_entries_by_group = {
        "General": [
            {"_runID": "R1", "verb": "Test",
             "adverbs": {"tomato": "q"},
             "data_entry": {"Instrument": "HPLC-03"}},
            {"_runID": "R1", "verb": "Test",  # duplicate without override
             "adverbs": {"tomato": "x"},
             "data_entry": {"Instrument": "HPLC-03"}}
        ]
    }
    override_index = {}  # no aliases, so duplicate should error

    result = audit_all(
        noun_types=noun_types,
        verb_types=verb_types,
        adverb_types=adverb_types,
        adjective_types=adjective_types,
        noun_instances_by_type=noun_instances_by_type,
        run_entries_by_group=run_entries_by_group,
        noun_index=noun_index,
        override_index=override_index,
    )
    from pprint import pprint
    pprint(result["summary"])
    for f in result["findings"]:
        pprint(f)
