"""Back-compat shim — the single IdService lives in :mod:`utils.id_generator`.

This module historically carried a near-duplicate of ``utils/id_generator.py`` (the duplicate-ID
race R1 lived in BOTH and was closed in both by serializing the ``autogen_counters.json``
read-increment-write under ``utils.atomic.file_lock`` + ``atomic_write_json``). The two copies have
since fully converged: ``generate_autogenerated_id`` / ``generate_hex_segment`` /
``generate_date_segment`` / ``list_date_formats`` are byte-identical, and this module's logger-based
``prompt_date_format`` equals ``utils.core_prompt_date_format``.

Collapse to ONE implementation so the locked IdService (atomic, file-locked counter R-M-W, and the
mixed-schema ``autogen_counters.json`` tolerance — ``.get(prefix, -1)`` + whole-dict round-trip that
LIMS-System relies on) has a single home. Core callers (``noun_workbench_gui`` /
``runlog_workbench_gui`` / ``core_noun`` — all use only ``generate_autogenerated_id``) are
unaffected. Re-exporting ``core_prompt_date_format`` as ``prompt_date_format`` also retires this
module's latent ``indexed_choice`` NameError (the name was used but never imported here; ``utils``
imports it).
"""
from utils.id_generator import (
    core_prompt_date_format as prompt_date_format,
    generate_autogenerated_id,
    generate_date_segment,
    generate_hex_segment,
    list_date_formats,
)

__all__ = [
    "generate_autogenerated_id",
    "generate_hex_segment",
    "generate_date_segment",
    "list_date_formats",
    "prompt_date_format",
]
