from datetime import datetime
from pathlib import Path
import json
from typing import Any, Set, Optional
import logging
logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)

def list_date_formats() -> dict[str, str]:
    """
    Returns a dictionary of date format keys to their example outputs
    based on today's date. Used for prompting.
    """
    today = datetime.today()
    return {
        "mmddyy":    today.strftime("%m%d%y"),
        "mmddyyyy":  today.strftime("%m%d%Y"),
        "yymmdd":    today.strftime("%y%m%d"),
        "yyyymmdd":  today.strftime("%Y%m%d"),
        "mmdd":      today.strftime("%m%d"),
        "ddmm":      today.strftime("%d%m"),
        "dd":        today.strftime("%d"),
        "mm":        today.strftime("%m"),
        "yy":        today.strftime("%y"),
        "yyyy":      today.strftime("%Y"),
        "ddmmyyyy":  today.strftime("%d%m%Y"),
        "ddmmyy":    today.strftime("%d%m%y"),
    }

def prompt_date_format() -> Optional[str]:
    formats = list_date_formats()
    keys = list(formats.keys())
    previews = [f"{k} → {formats[k]}" for k in keys]

    logger.info("📆 Choose a date format for this segment:")
    idx = indexed_choice(previews, prompt_msg="Date format")
    if idx is None:
        return None
    return keys[idx]

def generate_date_segment(fmt: str) -> str:
    """
    Convert a “mmddyyyy”‐style format string into a Python strftime format
    and return the current date. If fmt is invalid, return an empty string.
    """
    now = datetime.now()
    try:
        python_fmt = (
            fmt.replace("mm", "%m")
               .replace("dd", "%d")
               .replace("yyyy", "%Y")
               .replace("yy", "%y")
        )
        return now.strftime(python_fmt)
    except Exception:
        return ""


def generate_date_segment(fmt: str) -> str:
    now = datetime.now()
    try:
        python_fmt = (
            fmt.replace("yyyy", "%Y")
               .replace("yy",   "%y")
               .replace("mm",   "%m")
               .replace("dd",   "%d")
        )
        return now.strftime(python_fmt)
    except Exception:
        return ""

def generate_hex_segment(start_int: int, offset: int, width: int) -> str:
    candidate = start_int + offset
    return f"{candidate:0{width}X}"

def generate_autogenerated_id(
    noun_type_name: str,
    noun_schema: dict[str, Any],
    noun_types_path: Path,
    existing_ids: Set[str]
) -> str:
    """
    1) Reads noun_schema['autogenerate_segments']
    2) Builds a prefix from all STATIC/DATE segments up to the first INCREMENTABLE
       segment (type in {"number","letter","hex"})
    3) Loads (or creates) autogen_counters.json → { noun: { prefix: last_count } }
    4) Increments that count, formats suffix (number/letter/hex), loops until unique
    5) Persists the new count and returns prefix+suffix
    """
    # 1) Pull segments
    fmt_segments = noun_schema.get("autogenerate_segments")
    if not fmt_segments:
        raise ValueError(f"autogenerate_segments missing in schema for '{noun_type_name}'")

    # 2) Find the first incrementable segment
    inc_index: Optional[int] = next(
        (i for i,s in enumerate(fmt_segments) if s.get("type") in {"number","letter","hex"}),
        None
    )
    if inc_index is None:
        raise ValueError(f"No incrementable segment in autogenerate_segments for '{noun_type_name}'")

    # 3) Build the prefix from STATIC and DATE segments before inc_index
    prefix = ""
    for seg in fmt_segments[:inc_index]:
        t = seg.get("type")
        if t == "static":
            prefix += seg.get("value","")
        elif t == "date":
            prefix += generate_date_segment(seg.get("format",""))

    # 4) Load or initialize counters file
    project_path   = noun_types_path.parent
    counters_path  = project_path / "autogen_counters.json"
    if counters_path.exists():
        with open(counters_path) as f:
            counters = json.load(f)
    else:
        counters = {}

    noun_counters = counters.setdefault(noun_type_name, {})
    last_count    = noun_counters.get(prefix, -1)

    # 5) Loop to find a unique suffix
    count   = last_count + 1
    inc_seg = fmt_segments[inc_index]
    seg_type = inc_seg.get("type")

    while True:
        if seg_type == "number":
            width  = int(inc_seg.get("length",0))
            suffix = f"{count:0{width}d}"
        elif seg_type == "letter":
            suffix = chr(65 + (count % 26))
        elif seg_type == "hex":
            width    = int(inc_seg.get("length",0))
            base_int = int(inc_seg.get("start","0"),16)
            suffix   = generate_hex_segment(base_int, count, width)
        else:
            raise ValueError(f"Unknown incrementable segment type '{seg_type}' in schema for '{noun_type_name}'")

        candidate = prefix + suffix
        if candidate not in existing_ids:
            # 6) Persist updated counter and return
            noun_counters[prefix] = count
            counters[noun_type_name] = noun_counters
            with open(counters_path,"w") as f:
                json.dump(counters, f, indent=2)
            return candidate

        count += 1