# core/audit/checks.py
# Type/value checking helpers, dedupe, and the autogenerated-ID regex compiler.
# Split VERBATIM from core_audit.py (the R19 integrity auditor).

from __future__ import annotations
from typing import Any, Iterable, List, Tuple
import re

from utils.logger import get_logger
log = get_logger(__name__)


# -------------------------------
# Helpers: type & value checking
# -------------------------------

def _is_type(value: Any, t: str) -> bool:
    """Loose, pragmatic type check aligned with GIMS field types."""
    # NOTE: This is called very frequently; keep debug lightweight.
    t_orig = t
    if value is None:
        log.debug("[_is_type] value=None fails for type", t_orig)
        return False
    t = t.lower()
    if t in ("string", "str", "text"):
        ok = isinstance(value, str)
    elif t in ("number", "float", "double", "decimal"):
        ok = isinstance(value, (int, float)) and not isinstance(value, bool)
    elif t in ("int", "integer"):
        ok = isinstance(value, int) and not isinstance(value, bool)
    elif t in ("bool", "boolean"):
        ok = isinstance(value, bool)
    elif t == "date":
        ok = isinstance(value, str) and bool(re.match(r"^\d{4}-\d{2}-\d{2}$", value))
    elif t in ("reference", "ref"):
        ok = isinstance(value, str)
    elif t in ("enum", "tag"):
        ok = isinstance(value, (str, list))
    else:
        ok = True  # Unknown types pass
    log.debug("[_is_type]", repr(value), "as", t_orig, "->", ok)
    return ok


def _dedupe(seq: Iterable[Any]) -> Tuple[List[Any], List[Any]]:
    """Return (unique_in_order, duplicates_in_order)."""
    log.debug("[_dedupe] Start")
    seen = set()
    uniques, dups = [], []
    for x in seq:
        if x in seen:
            dups.append(x)
        else:
            seen.add(x)
            uniques.append(x)
    log.debug("[_dedupe] uniques:", uniques, "dups:", dups)
    return uniques, dups


# -------------------------------
# Autogenerated ID compiler
# -------------------------------

# Supported segments (aligning with your ID generator):
# - static: {"type": "static", "value": "SMP"}
# - date: {"type": "date", "format": "YYYYMMDD"}  # you control formats in backend
# - number: {"type": "number", "width": 3}        # zero-padded
# - letter: {"type": "letter", "width": 2}        # [A-Z]{width}
# - hex: {"type": "hex", "width": 4}              # [0-9A-F]{width}

_DATE_TOKEN_MAP = {
    "YYYY": r"\d{4}",
    "YY":   r"\d{2}",
    "MM":   r"\d{2}",
    "DD":   r"\d{2}",
}

def compile_autogen_regex(segments: list[dict]) -> re.Pattern:
    """
    Build a regex pattern from autogenerate_segments in noun_types.
    Supports:
      - static: {"type": "static", "value": "LOL"}
      - date:   {"type": "date", "format": "MMDDYYYY"} (case-insensitive)
      - number: {"type": "number", "width": 3} or {"length": 3}
      - hex:    {"type": "hex", "width": 4} or {"length": 4}
      - letter: {"type": "letter", "width": 2}
    """
    parts = []
    for seg in segments or []:
        stype = (seg.get("type") or "").lower()
        if stype == "static":
            val = str(seg.get("value", ""))
            parts.append(re.escape(val))

        elif stype == "date":
            fmt = str(seg.get("format", "YYYYMMDD")).upper()
            pattern = re.escape(fmt)
            for tok, rx in _DATE_TOKEN_MAP.items():
                pattern = pattern.replace(re.escape(tok), rx)
            parts.append(pattern)

        elif stype == "number":
            w = int(seg.get("width") or seg.get("length") or 1)
            parts.append(rf"\d{{{w}}}")

        elif stype == "hex":
            w = int(seg.get("width") or seg.get("length") or 1)
            parts.append(rf"[0-9A-F]{{{w}}}")

        elif stype == "letter":
            w = int(seg.get("width") or seg.get("length") or 1)
            parts.append(rf"[A-Z]{{{w}}}")

        else:
            # Fallback: accept any non-empty string
            parts.append(r".+")

    regex = "^" + "".join(parts) + "$"
    return re.compile(regex)
