"""Atomic file writes and cross-platform advisory file locking.

A small, dependency-free kernel primitive. It is the seed of the proposal's single
``AtomicStore`` (Phase 5); for now it backs lock-safe autogenerated-ID minting (R1) so
concurrent requests cannot read the same counter and mint duplicate IDs.

- ``file_lock(target)``      — exclusive advisory lock, serialized across threads AND
                                processes (e.g. ``uvicorn --workers N``).
- ``atomic_write_text/json`` — write-to-temp-in-same-dir then ``os.replace`` so readers
                                never observe a half-written file.
"""
from __future__ import annotations

import json
import os
import tempfile
from contextlib import contextmanager
from pathlib import Path
from typing import Any, Iterator, Union

try:  # POSIX (Linux, macOS) — the primary targets
    import fcntl

    _HAVE_FCNTL = True
except ImportError:  # pragma: no cover - Windows fallback
    _HAVE_FCNTL = False
    try:
        import msvcrt
    except ImportError:  # pragma: no cover
        msvcrt = None  # type: ignore[assignment]

PathLike = Union[str, os.PathLike]


@contextmanager
def file_lock(target: PathLike) -> Iterator[None]:
    """Hold an exclusive advisory lock keyed on ``target`` for the ``with`` body.

    Locks a sidecar ``<target>.lock`` file (so the data file itself can be atomically
    replaced while the lock is held). Blocks until the lock is acquired. Best-effort on
    exotic platforms lacking both ``fcntl`` and ``msvcrt`` (degrades to no-op).
    """
    lock_path = Path(str(target) + ".lock")
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(str(lock_path), os.O_RDWR | os.O_CREAT, 0o644)
    try:
        if _HAVE_FCNTL:
            fcntl.flock(fd, fcntl.LOCK_EX)
        elif msvcrt is not None:  # pragma: no cover - Windows
            os.lseek(fd, 0, os.SEEK_SET)
            msvcrt.locking(fd, msvcrt.LK_LOCK, 1)
        yield
    finally:
        try:
            if _HAVE_FCNTL:
                fcntl.flock(fd, fcntl.LOCK_UN)
            elif msvcrt is not None:  # pragma: no cover - Windows
                os.lseek(fd, 0, os.SEEK_SET)
                msvcrt.locking(fd, msvcrt.LK_UNLCK, 1)
        finally:
            os.close(fd)


def atomic_write_text(path: PathLike, data: str, encoding: str = "utf-8") -> None:
    """Atomically write ``data`` to ``path`` (temp file in same dir + ``os.replace``)."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(p.parent), prefix=f".{p.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding=encoding) as f:
            f.write(data)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, p)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def atomic_write_json(path: PathLike, obj: Any, indent: int = 2) -> None:
    """Atomically serialize ``obj`` to JSON at ``path``."""
    atomic_write_text(path, json.dumps(obj, indent=indent))


def atomic_write_bytes(path: PathLike, data: bytes) -> None:
    """Atomically write ``data`` bytes to ``path`` (temp file in same dir + ``os.replace``)."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=str(p.parent), prefix=f".{p.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "wb") as f:
            f.write(data)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, p)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
