# tools/create_item.py

import sys
from pathlib import Path

# ─ Ensure `utils/` is on sys.path ─────────────────────────────────────────────
PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))
# ─────────────────────────────────────────────────────────────────────────────

import argparse
import csv
import json
from datetime import datetime
import shutil

from utils.interface import prompt_if_missing, indexed_choice, menu_prompt
from utils.handlers.noun import NounType
from utils.file_ops import upload_file_to_folder
from utils.semantics import is_valid_date, validate_item_against_schema
from utils.handlers.adjective import ActionRequirementAdjective
from utils.id_generator import generate_autogenerated_id
from utils.handlers.adjective import load_adjective_handler

TEMP_UPLOAD = Path(".temp_upload.csv")


def list_available_nouns(project_path: Path) -> list:
    noun_file = project_path / "noun_types.json"
    if not noun_file.exists():
        print("❌ No noun_types.json found.")
        return []
    with open(noun_file) as f:
        return list(json.load(f).keys())



def prompt_for_fields(noun_type: NounType) -> dict:
    data: dict[str, str] = {}
    schema       = noun_type.schema
    project_path = noun_type.project_path
    noun_type    = noun_type.name

    # ——— Load noun_types & adjective_types so we can override ftype —————
    noun_types_path       = project_path / "noun_types.json"
    all_noun_defs         = json.loads(noun_types_path.read_text())
    adjective_defs_path   = project_path / "adjective_types.json"
    adjective_defs        = json.loads(adjective_defs_path.read_text())
    # build a lookup of field_name → adjective entry for this noun
    field2adj = {
        adj["adjective"]: adj
        for adj in adjective_defs
        if noun_type in adj.get("applies_to", [])
    }

    # ——— Prepare existing IDs for autogen ——————————————
    primary_id_field = schema.get("primary_id_field")
    autogen_enabled  = schema.get("autogenerate_id", False)
    existing_ids: set[str] = set()
    if autogen_enabled and primary_id_field:
        items_file = project_path / "nouns" / noun_type / "items.jsonl"
        if items_file.exists():
            for line in items_file.read_text().splitlines():
                if not line.strip():
                    continue
                rec = json.loads(line)
                pid = rec.get(primary_id_field)
                if pid:
                    existing_ids.add(str(pid))

    # ——— Loop over each declared field ——————————————
    for field_name, field_info in schema.get("fields", {}).items():
        required = field_info.get("required", False)

        # — Autogen your own ID? ——
        if autogen_enabled and field_name == primary_id_field:
            new_id = generate_autogenerated_id(
                noun_type_name=noun_type,
                noun_schema=schema,
                noun_types_path=noun_types_path,
                existing_ids=existing_ids
            )
            print(f"🔧 Autogenerated '{field_name}': {new_id}")
            data[field_name] = new_id
            continue

        # — Override ftype if there's an adjective registered ——
        if field_name in field2adj:
            ftype = "adjective"
        else:
            ftype = field_info.get("type")

        # — Handle adjective/reference prompts ——
        if ftype == "adjective":
            adj        = field2adj[field_name]
            handler    = load_adjective_handler(
                project_path,
                noun_type,
                field_name,
                verb_types=None
            )
            # if it's a Reference, the handler knows adj["reference_noun"]
            reference_noun = handler.data.get("reference_noun") or adj.get("reference_noun")
            # figure out where that reference’s items live:
            ref_items_file = project_path / "nouns" / reference_noun / "items.jsonl"

            if ref_items_file.exists() and ref_items_file.read_text().strip():
                # there *are* existing entries → show your indexed picker
                val = handler.prompt_instance_edit(field_name, "")
            else:
                # no entries yet → free-form string (or force required)
                prompt = f"Enter value for '{field_name}' (string)"
                if required:
                    prompt += " [required]"
                prompt += ": "
                while True:
                    val = input(prompt).strip()
                    if not val and required:
                        print("❌ Required field. Please enter a value.")
                        continue
                    break

            if required and not val:
                raise ValueError(f"Field '{field_name}' is required.")
            data[field_name] = val
            continue

        # — Normal scalar fields ——
        prompt = f"Enter value for '{field_name}' ({ftype})"
        if required:
            prompt += " [required]"
        prompt += ": "

        while True:
            val = input(prompt).strip()
            if not val:
                if required:
                    print("❌ Required field. Please enter a value.")
                    continue
                else:
                    break

            if ftype == "date" and not is_valid_date(val, fmt="yyyy-mm-dd"):
                print("❌ Invalid date format. Use YYYY-MM-DD.")
                continue

            # other type checks...
            break

        data[field_name] = val

    return data

def add_items(project_path: Path, noun_type: str, csv_arg: Path = None):
    noun_file = project_path / "noun_types.json"
    items_file = project_path / "nouns" / noun_type / "items.jsonl"

    if not noun_file.exists():
        raise FileNotFoundError("noun_types.json not found in project.")

    noun_data = json.loads(noun_file.read_text())
    noun_schema = noun_data.get(noun_type)
    if not noun_schema:
        raise ValueError(f"Noun '{noun_type}' not found in noun_types.json.")

    noun_type = NounType(noun_type, noun_schema, noun_file)
    noun_type.project_path = project_path  # for adjective lookup

    items: list[dict] = []

    def handle_csv(path: Path):
        valid: list[dict] = []
        invalid: list[tuple[int, list[str]]] = []
        with open(path) as f:
            reader = csv.DictReader(f)
            for i, row in enumerate(reader, start=1):
                errors = validate_item_against_schema(row, noun_type)
                if errors:
                    invalid.append((i, errors))
                else:
                    valid.append(row)

        if invalid:
            print(f"❌ {len(invalid)} invalid row(s) detected:")
            for i, errs in invalid:
                print(f"  • Row {i}:")
                for e in errs:
                    print(f"     - {e}")
            choice = input("Continue uploading the valid rows? (y/N): ").strip().lower()
            if not choice.startswith("y"):
                print("🚫 Upload cancelled.")
                return None
        return valid

    if csv_arg:
        # Direct CSV import via --csv
        result = handle_csv(csv_arg)
        if result is None:
            return
        items.extend(result)

    else:
        # Interactive choice: CSV, manual, or quit
        options = {
            "c": "CSV upload",
            "m": "Manual entry",
            "q": "Quit"
        }
        while True:
            choice = menu_prompt(options)  # prints "(c)SV upload", "(m)anual entry", "(q)uit" and returns one key
            if choice == "q":
                print("👋 Aborting entry.")
                return                     # or break if you want to return to a higher menu

            if choice == "c":
                print("📂 Opening file picker for CSV…")
                uploaded_file = upload_file_to_folder(TEMP_UPLOAD)
                if not uploaded_file:
                    print("❌ No CSV selected. Returning to menu.")
                    # Previously: continue
                    return   # Or break, or raise, depending on UX preference
                result = handle_csv(uploaded_file)
                uploaded_file.unlink()
                if result is None:
                    return
                items.extend(result)

                #Optional: clean up TEMP_UPLOAD folder if desired
                shutil.rmtree(TEMP_UPLOAD)

                break

            if choice == "m":
                try:
                    item = prompt_for_fields(noun_type)
                except ValueError as e:
                    print(f"❌ {e}. Try again.")
                    continue
                items.append(item)
                break

    # If still no items, force manual
    if not items:
        print("⚠️ No valid items found. Switching to manual entry.")
        while True:
            try:
                item = prompt_for_fields(noun_type)
            except ValueError as e:
                print(f"❌ {e}. Try again.")
                continue
            items.append(item)
            break

    # Validate uniqueness for Reference adjectives
    from utils.handlers.adjective import load_adjective_handler
    context = {"noun_type": noun_type, "project_path": project_path}
    errors: list[str] = []

    for field_name, field_info in noun_type.schema.get("fields", {}).items():
        if field_info.get("type") != "adjective":
            continue
        try:
            handler = load_adjective_handler(project_path, noun_type, field_name)
            if hasattr(handler, "validate_entries"):
                errors += handler.validate_entries(items, context)
        except Exception as e:
            print(f"[warn] Skipping validation for {field_name}: {e}")
    if errors:
        for e in errors:
            print(e)
        return

    # Persist to items.jsonl
    items_file.parent.mkdir(parents=True, exist_ok=True)
    with open(items_file, "a") as f:
        for item in items:
            f.write(json.dumps(item) + "\n")

    print(f"✅ Added {len(items)} item(s) to '{noun_type}'.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("project", nargs="?", help="Name of the project")
    parser.add_argument("--noun", help="Noun type to create item for")
    parser.add_argument("--csv", help="Path to CSV for bulk import")
    args = parser.parse_args()

    project_root = PROJECT_ROOT / "projects"
    project = prompt_if_missing(
        args.project,
        [p.name for p in project_root.iterdir() if p.is_dir()],
        label="project"
    )
    project_path = project_root / project

    noun = prompt_if_missing(
        args.noun,
        list_available_nouns(project_path),
        label="noun type"
    )

    csv_path = Path(args.csv) if args.csv else None
    add_items(project_path, noun, csv_path)
