import pytest
import json
from pathlib import Path
from utils import id_generator as ig
import datetime


def test_generate_date_segment_valid():
    seg = ig.generate_date_segment("mmddyyyy")
    assert len(seg) == 8


def test_generate_date_segment_invalid():
    assert ig.generate_date_segment("invalid") == "invalid"


def test_generate_hex_segment():
    assert ig.generate_hex_segment(0x10, 1, 4) == "0011"


def test_generate_autogenerated_id(tmp_path):
    schema = {
        "autogenerate_segments": [
            {"type": "static", "value": "S"},
            {"type": "number", "length": 3}
        ]
    }
    counters = tmp_path / "autogen_counters.json"
    noun_types = tmp_path / "noun_types.json"
    noun_types.write_text("{}")
    result = ig.generate_autogenerated_id("Sample", schema, noun_types, set())
    assert result.startswith("S")
    data = json.loads(counters.read_text())
    assert data["Sample"]["S"] == 0

# Additional tests

def test_list_date_formats_contains_keys():
    fmts = ig.list_date_formats()
    for key in ["mmddyy", "yyyy"]:
        assert key in fmts


def test_prompt_date_format_select(monkeypatch):
    monkeypatch.setattr(ig, "indexed_choice", lambda opts, prompt_msg="": 0)
    result = ig.prompt_date_format()
    assert result in ig.list_date_formats()


def test_prompt_date_format_cancel(monkeypatch):
    monkeypatch.setattr(ig, "indexed_choice", lambda opts, prompt_msg="": None)
    assert ig.prompt_date_format() is None


def test_autogenerated_id_increments(tmp_path):
    schema = {
        "autogenerate_segments": [
            {"type": "static", "value": "X"},
            {"type": "number", "length": 2}
        ]
    }
    noun_types = tmp_path / "noun_types.json"
    noun_types.write_text("{}")
    result1 = ig.generate_autogenerated_id("Sample", schema, noun_types, set())
    result2 = ig.generate_autogenerated_id("Sample", schema, noun_types, {result1})
    assert result1 != result2


def test_autogenerated_id_letter(tmp_path):
    schema = {"autogenerate_segments": [{"type":"static","value":"A"},{"type":"letter"}]}
    noun_types = tmp_path / "noun_types.json"
    noun_types.write_text("{}")
    id_val = ig.generate_autogenerated_id("N", schema, noun_types, set())
    assert id_val.endswith("A")


def test_autogenerated_id_hex(tmp_path):
    schema = {"autogenerate_segments": [{"type":"hex","start":"0","length":2}]}
    noun_types = tmp_path / "noun_types.json"
    noun_types.write_text("{}")
    id_val = ig.generate_autogenerated_id("N", schema, noun_types, set())
    assert id_val == "00"


def test_autogenerated_id_errors(tmp_path):
    noun_types = tmp_path / "noun_types.json"
    noun_types.write_text("{}")
    with pytest.raises(ValueError):
        ig.generate_autogenerated_id("N", {}, noun_types, set())

def test_generate_date_segment_empty():
    assert ig.generate_date_segment("") == ""

def test_generate_date_segment_partial_tokens():
    # Should not throw, might just pass literals
    result = ig.generate_date_segment("ddmm____")
    assert isinstance(result, str)

def test_generate_hex_segment_overflow():
    result = ig.generate_hex_segment(0xFF, 1, 2)
    assert result == "100"

def test_generate_autogenerated_id_full_prefix(tmp_path):
    schema = {
        "autogenerate_segments": [
            {"type": "static", "value": "X"},
            {"type": "static", "value": "Y"},
            {"type": "date", "format": "yy"},
            {"type": "number", "length": 2}
        ]
    }
    noun_types = tmp_path / "noun_types.json"
    noun_types.write_text("{}")
    result = ig.generate_autogenerated_id("N", schema, noun_types, set())
    # The prefix should include "XY" followed by the two-digit year
    expected_prefix = "XY" + datetime.datetime.now().strftime("%y")
    assert result.startswith(expected_prefix)

def test_generate_autogenerated_id_multiple_incrementables(tmp_path):
    schema = {
        "autogenerate_segments": [
            {"type": "static", "value": "A"},
            {"type": "number", "length": 2},
            {"type": "letter"},
            {"type": "hex", "start": "0", "length": 2}
        ]
    }
    noun_types = tmp_path / "noun_types.json"
    noun_types.write_text("{}")
    val = ig.generate_autogenerated_id("Thing", schema, noun_types, set())
    assert val.startswith("A")

def test_generate_autogenerated_id_skips_existing(tmp_path):
    schema = {
        "autogenerate_segments": [
            {"type": "static", "value": "X"},
            {"type": "number", "length": 2}
        ]
    }
    noun_types = tmp_path / "noun_types.json"
    noun_types.write_text("{}")
    val1 = ig.generate_autogenerated_id("T", schema, noun_types, set())
    val2 = ig.generate_autogenerated_id("T", schema, noun_types, {val1})
    assert val1 != val2
    assert val2.endswith("01")  # val1 ends in 00, next is 01

def test_generate_autogenerated_id_unrelated_counters(tmp_path):
    counters_path = tmp_path / "autogen_counters.json"
    counters_path.write_text(json.dumps({"Other": {"PRE": 99}}))
    schema = {
        "autogenerate_segments": [
            {"type": "static", "value": "PRE"},
            {"type": "number", "length": 2}
        ]
    }
    noun_types = tmp_path / "noun_types.json"
    noun_types.write_text("{}")
    val = ig.generate_autogenerated_id("New", schema, noun_types, set())
    assert val.endswith("00")  # Should ignore "Other" noun

def test_generate_autogenerated_id_unknown_incrementable_type(tmp_path):
    schema = {
        "autogenerate_segments": [
            {"type": "static", "value": "Z"},
            {"type": "unknown"}
        ]
    }
    noun_types = tmp_path / "noun_types.json"
    noun_types.write_text("{}")
    # Since no valid incrementable segment is found, it should error accordingly
    with pytest.raises(ValueError, match="No incrementable segment"):
        ig.generate_autogenerated_id("N", schema, noun_types, set())