import json
import csv
import pytest
import builtins
from pathlib import Path

from tools.create_item import (
    list_available_nouns,
    prompt_for_fields,
    add_items,
    TEMP_UPLOAD
)

# Fixtures
@pytest.fixture(autouse=True)
def change_cwd(tmp_path, monkeypatch):
    # Ensure all file I/O is under tmp_path for isolation
    monkeypatch.chdir(tmp_path)
    return tmp_path

@pytest.fixture
def tmp_project(tmp_path):
    # Create project and a basic noun_types.json
    project = tmp_path / "projects" / "TestProj"
    project.mkdir(parents=True)
    noun_types = {"Sample": {"fields": {"id": {"type": "string", "required": True}}, "primary_id_field": "id"}}
    (project / "noun_types.json").write_text(json.dumps(noun_types))
    # create empty adjective_types.json expected by prompt_for_fields
    (project / "adjective_types.json").write_text("[]")
    return project

# ----------------------------
# Tests for list_available_nouns
# ----------------------------

def test_list_available_nouns_no_file(change_cwd, capsys):
    # No noun_types.json
    result = list_available_nouns(Path("nonexistent"))
    assert result == []
    assert "❌ No noun_types.json found." in capsys.readouterr().out


def test_list_available_nouns(tmp_project):
    nouns = list_available_nouns(tmp_project)
    assert nouns == ["Sample"], "Should list the 'Sample' noun"

# ----------------------------
# Tests for prompt_for_fields
# ----------------------------

def test_prompt_for_fields_basic(tmp_project, monkeypatch):
    from utils.handlers.noun import NounType
    # Setup a simple schema with string and date
    schema = {
        "fields": {
            "name": {"type": "string", "required": True},
            "event_date": {"type": "date", "required": False}
        }
    }
    noun_file = tmp_project / "noun_types.json"
    # Overwrite schema
    (noun_file).write_text(json.dumps({"Sample": schema}))
    noun_type = NounType("Sample", schema, noun_file)
    noun_type.project_path = tmp_project

    # Simulate inputs: empty name -> 'Alice'; invalid date->'2021-13-01'; valid->'2021-12-01'
    inputs = iter(["", "Alice", "2021-13-01", "2021-12-01"])
    monkeypatch.setattr("builtins.input", lambda prompt="": next(inputs))
    monkeypatch.setattr("tools.create_item.is_valid_date", lambda val, fmt: val == "2021-12-01")

    data = prompt_for_fields(noun_type)
    assert data["name"] == "Alice"
    assert data["event_date"] == "2021-12-01"


def test_prompt_for_fields_autogen(tmp_project, monkeypatch):
    from utils.handlers.noun import NounType
    # Schema with autogen primary ID and an extra field
    schema = {
        "fields": {"id": {"type": "string"}, "note": {"type": "string"}},
        "primary_id_field": "id",
        "autogenerate_id": True
    }
    noun_file = tmp_project / "noun_types.json"
    (noun_file).write_text(json.dumps({"Sample": schema}))
    noun_type = NounType("Sample", schema, noun_file)
    noun_type.project_path = tmp_project

    # Create existing items.jsonl with one record
    items_dir = tmp_project / "nouns" / "Sample"
    items_dir.mkdir(parents=True)
    items_file = items_dir / "items.jsonl"
    items_file.write_text(json.dumps({"id": "001"}) + "\n")

    # Stub ID generator
    monkeypatch.setattr("tools.create_item.generate_autogenerated_id", lambda **kwargs: "002")
    # Stub input for note
    monkeypatch.setattr("builtins.input", lambda prompt="": "TestNote")

    data = prompt_for_fields(noun_type)
    assert data["id"] == "002"
    assert data["note"] == "TestNote"


def test_prompt_for_fields_adjective_required(tmp_project, monkeypatch):
    from utils.handlers.noun import NounType
    # Schema with adjective field required
    schema = {"fields": {"req": {"type": "adjective", "required": True}}}
    noun_file = tmp_project / "noun_types.json"
    noun_file.write_text(json.dumps({"Sample": schema}))
    # ensure adjective is defined so prompt_for_fields treats field as adjective
    (tmp_project / "adjective_types.json").write_text(json.dumps([
        {"adjective": "req", "applies_to": ["Sample"], "adjective_class": "Tag"}
    ]))
    # add an items file so handler path chooses prompt_instance_edit
    items_dir = tmp_project / "nouns" / "Sample"
    items_dir.mkdir(parents=True, exist_ok=True)
    (items_dir / "items.jsonl").write_text(json.dumps({"sample_id": "S1"}) + "\n")
    noun_type = NounType("Sample", schema, noun_file)
    noun_type.project_path = tmp_project

    class FakeHandler:
        def __init__(self):
            self.data = {"reference_noun": "Sample"}
        def prompt_instance_edit(self, name, val):
            return ""
    monkeypatch.setattr(
        "tools.create_item.load_adjective_handler",
        lambda project_path, noun_name, field_name, verb_types=None: FakeHandler()
    )
    with pytest.raises(ValueError):
        prompt_for_fields(noun_type)

# ----------------------------
# Tests for add_items
# ----------------------------

def test_add_items_no_noun_file(change_cwd):
    with pytest.raises(FileNotFoundError):
        add_items(Path("."), "Sample")


def test_add_items_noun_not_found(tmp_project):
    # Remove Sample key
    (tmp_project / "noun_types.json").write_text(json.dumps({}))
    with pytest.raises(ValueError):
        add_items(tmp_project, "Sample")


def test_add_items_csv_invalid(tmp_project, monkeypatch, capsys):
    # Prepare short schema
    (tmp_project / "noun_types.json").write_text(json.dumps({"Sample": {"fields": {}}}))
    (tmp_project / "nouns" / "Sample").mkdir(parents=True)
    # Create CSV with one valid, one invalid row
    csv_path = Path("data.csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["id", "name"]); w.writerow(["1", "Alice"]); w.writerow(["2", ""])

    # Stub validation
    monkeypatch.setattr(
        "tools.create_item.validate_item_against_schema",
        lambda row, nt: [] if row["name"] else ["Missing name"]
    )
    # Simulate 'n' to cancel
    monkeypatch.setattr("builtins.input", lambda prompt="": "n")

    result = add_items(tmp_project, "Sample", csv_path)
    assert result is None
    out = capsys.readouterr().out
    assert "invalid row(s)" in out.lower()


def test_add_items_csv_valid(tmp_project, monkeypatch, capsys):
    (tmp_project / "noun_types.json").write_text(json.dumps({"Sample": {"fields": {}}}))
    (tmp_project / "nouns" / "Sample").mkdir(parents=True)
    csv_path = Path("data.csv")
    with open(csv_path, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["id", "name"]); w.writerow(["1", "Alice"]); w.writerow(["2", ""])

    monkeypatch.setattr(
        "tools.create_item.validate_item_against_schema",
        lambda row, nt: [] if row["name"] else ["Missing name"]
    )
    monkeypatch.setattr("builtins.input", lambda prompt="": "y")

    add_items(tmp_project, "Sample", csv_path)
    items_file = tmp_project / "nouns" / "Sample" / "items.jsonl"
    lines = items_file.read_text().splitlines()
    assert json.loads(lines[0]) == {"id": "1", "name": "Alice"}
    assert "✅ Added 1 item" in capsys.readouterr().out


def test_add_items_manual(tmp_project, monkeypatch, capsys):
    # Prepare schema for manual
    (tmp_project / "noun_types.json").write_text(json.dumps({"Sample": {"fields": {}}}))
    # Stub prompt_for_fields
    monkeypatch.setattr("tools.create_item.prompt_for_fields", lambda nt: {"a": "b"})
    monkeypatch.setattr("builtins.input", lambda prompt="": "m")

    add_items(tmp_project, "Sample", None)
    items_file = tmp_project / "nouns" / "Sample" / "items.jsonl"
    assert json.loads(items_file.read_text().splitlines()[0]) == {"a": "b"}
    assert "✅ Added 1 item" in capsys.readouterr().out


def test_add_items_csv_fallback(tmp_project, monkeypatch):
    (tmp_project / "noun_types.json").write_text(json.dumps({"Sample": {"fields": {}}}))

    # Simulate upload failure
    monkeypatch.setattr("tools.create_item.upload_file_to_folder", lambda *a, **k: None)

    # Stub menu_prompt: first choose CSV ('c'), then quit ('q')
    choices = iter(["c", "q"])
    monkeypatch.setattr("tools.create_item.menu_prompt", lambda opts: next(choices))

    # Prevent unexpected input() calls
    monkeypatch.setattr("builtins.input", lambda *a, **k: "q")

    add_items(tmp_project, "Sample", None)

    items_file = tmp_project / "nouns" / "Sample" / "items.jsonl"
    # Assert file was NOT created since upload failed and user quit
    assert not items_file.exists()